# Generated by Django 5.0.6 on 2026-09-14 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma', models.CharField(choices=[('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'PIX')], max_length=20)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('ESTORNADO', 'Estornado')], default='AGUARDANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoCartao',
            fields=[
                ('pagamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pagamento')),
                ('numeroCarta', models.CharField(max_length=19)),
                ('nomeTitular', models.CharField(max_length=150)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('bandeira', models.CharField(blank=True, max_length=30)),
            ],
            bases=('payments.pagamento',),
        ),
        migrations.CreateModel(
            name='PagamentoPIX',
            fields=[
                ('pagamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pagamento')),
                ('qrCode', models.TextField(blank=True)),
                ('codigoPix', models.CharField(blank=True, max_length=255)),
                ('dataExpiracao', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('payments.pagamento',),
        ),
    ]
