# Generated by Django 5.0.6 on 2026-09-14 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataEnvio', models.DateTimeField(blank=True, null=True)),
                ('previsaoEntrega', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_RETIRADA', 'Aguardando retirada'), ('A_CAMINHO', 'A caminho'), ('ENTREGUE', 'Entregue')], default='AGUARDANDO_RETIRADA', max_length=25)),
                ('codigoRastreio', models.CharField(blank=True, max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
